---
- name: Instalación Apache
  hosts: WebServers
  become: yes
  tasks:

    - name: Instalar Apache
      yum:
        name: httpd
        state: latest
    
    - name: Inicializar Apache
      service:
        name: httpd
        state: started
    
    - name: Configurar firewall para permitir servicio http
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

