---
- name: Actualizar página web
  hosts: WebServers
  become: yes
  tasks:

    - name: Copiar la página web personalizada
      copy: 
        src: pagina.html
        dest: /var/www/html/index.html

    - name: Reiniciar servicio de Apache
      service:
        name: httpd
        status: restarted 
